/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package monopoly.ui.screens.old;

import monopoly.beans.GameDetail;
import monopoly.beans.GameState;
import monopoly.ui.screen.controller.MonopolyDealHomeViewController;

/**
 *
 * @author Reena
 */
public class MonopolyDealHomeScreen extends javax.swing.JFrame {
    //<editor-fold defaultstate="collapsed" desc="comment">
    
    //</editor-fold>
    /*
     * Creates new form Sample
     */
    private MonopolyDealHomeViewController monopolyDealHomeScreenController = null;
    
    public MonopolyDealHomeScreen() {
        initComponents();
    }
    public MonopolyDealHomeScreen(GameDetail gameMoves, GameState gameState) {
        initComponents();
//        monopolyDealHomeScreenController =  new MonopolyDealHomeViewController(gameMoves, gameState);
//        monopolyDealHomeScreenController.setUpGame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        drawPileButton = new javax.swing.JButton();
        playPileButton = new javax.swing.JButton();
        drawCardsComboBox = new javax.swing.JComboBox();
        passTurnToNextPlayerButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        countOfCardsInDrawPileLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        countOfCardsInPlayPileLabel = new javax.swing.JLabel();
        turnIndicatorLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        viewCardsInBankButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        numberOfCardsInBankLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        sumOfValueOfCardsInBankLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        activityArea = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        viewCardsInHandButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        numberOfCardsInHandLabel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        showAllSetsButton = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        countOfCardsInAllSetsLabel = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        totalNumberOfDifferentSetsLabel = new javax.swing.JLabel();
        toggleActivityComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        showMyCardsButton = new javax.swing.JButton();
        showOpponentCardsButton = new javax.swing.JButton();
        remindTurnToOpponent = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1444, 481));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(0, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jPanel2.setMaximumSize(new java.awt.Dimension(360, 360));
        jPanel2.setMinimumSize(new java.awt.Dimension(360, 360));
        jPanel2.setPreferredSize(new java.awt.Dimension(360, 360));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Center Table");

        drawPileButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        drawPileButton.setText("Draw Pile");
        drawPileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawPileButtonActionPerformed(evt);
            }
        });

        playPileButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        playPileButton.setText("Play Pile");
        playPileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playPileButtonActionPerformed(evt);
            }
        });

        drawCardsComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        passTurnToNextPlayerButton.setText("Pass to next player");
        passTurnToNextPlayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passTurnToNextPlayerButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Count of cards in play pile:");

        countOfCardsInDrawPileLabel.setText("0");

        jLabel5.setText("Count of cards in draw pile:");

        countOfCardsInPlayPileLabel.setText("0");

        turnIndicatorLabel.setText("Turn indicator");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(drawCardsComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(countOfCardsInDrawPileLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(drawPileButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(countOfCardsInPlayPileLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(playPileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(passTurnToNextPlayerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                    .addComponent(turnIndicatorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(turnIndicatorLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drawCardsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passTurnToNextPlayerButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drawPileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playPileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countOfCardsInDrawPileLabel)
                    .addComponent(countOfCardsInPlayPileLabel))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(0, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jPanel3.setMaximumSize(new java.awt.Dimension(360, 360));
        jPanel3.setMinimumSize(new java.awt.Dimension(360, 360));
        jPanel3.setPreferredSize(new java.awt.Dimension(360, 360));

        viewCardsInBankButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        viewCardsInBankButton.setText("View cards in bank");
        viewCardsInBankButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCardsInBankButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Bank");

        jLabel9.setText("Number of Cards in Bank:");

        numberOfCardsInBankLabel.setText("0");

        jLabel11.setText("Total value of Cards in Bank:");

        sumOfValueOfCardsInBankLabel.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numberOfCardsInBankLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sumOfValueOfCardsInBankLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(viewCardsInBankButton, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewCardsInBankButton, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberOfCardsInBankLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sumOfValueOfCardsInBankLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        activityArea.setColumns(20);
        activityArea.setRows(5);
        activityArea.setMaximumSize(new java.awt.Dimension(164, 94));
        activityArea.setMinimumSize(new java.awt.Dimension(164, 94));
        jScrollPane1.setViewportView(activityArea);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(0, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jPanel6.setMaximumSize(new java.awt.Dimension(360, 360));
        jPanel6.setMinimumSize(new java.awt.Dimension(360, 360));
        jPanel6.setPreferredSize(new java.awt.Dimension(360, 360));

        viewCardsInHandButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        viewCardsInHandButton.setText("View cards in hand");
        viewCardsInHandButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCardsInHandButtonActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Hand Cards");

        jLabel14.setText("Number of Cards in Hand:");

        numberOfCardsInHandLabel.setText("0");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(viewCardsInHandButton, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addComponent(numberOfCardsInHandLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewCardsInHandButton, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberOfCardsInHandLabel))
                .addGap(18, 18, 18)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(0, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jPanel7.setMaximumSize(new java.awt.Dimension(360, 360));
        jPanel7.setMinimumSize(new java.awt.Dimension(360, 360));
        jPanel7.setPreferredSize(new java.awt.Dimension(360, 360));

        showAllSetsButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        showAllSetsButton.setText("Show all sets");
        showAllSetsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllSetsButtonActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Sets");

        jLabel19.setText("Number of Cards in all sets:");

        countOfCardsInAllSetsLabel.setText("0");

        jLabel21.setText("Number of different sets:");

        totalNumberOfDifferentSetsLabel.setText("0");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel18))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(showAllSetsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel19))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(countOfCardsInAllSetsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(totalNumberOfDifferentSetsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(showAllSetsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(countOfCardsInAllSetsLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalNumberOfDifferentSetsLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        toggleActivityComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("show view:");

        showMyCardsButton.setText("my cards");
        showMyCardsButton.setMaximumSize(new java.awt.Dimension(83, 23));
        showMyCardsButton.setMinimumSize(new java.awt.Dimension(83, 23));
        showMyCardsButton.setPreferredSize(new java.awt.Dimension(83, 23));
        showMyCardsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showMyCardsButtonActionPerformed(evt);
            }
        });

        showOpponentCardsButton.setText("Opponent");
        showOpponentCardsButton.setMaximumSize(new java.awt.Dimension(83, 23));
        showOpponentCardsButton.setMinimumSize(new java.awt.Dimension(83, 23));
        showOpponentCardsButton.setPreferredSize(new java.awt.Dimension(83, 23));
        showOpponentCardsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showOpponentCardsButtonActionPerformed(evt);
            }
        });

        remindTurnToOpponent.setText("Remind Trun");
        remindTurnToOpponent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remindTurnToOpponentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(toggleActivityComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(showMyCardsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(showOpponentCardsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(remindTurnToOpponent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(toggleActivityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(remindTurnToOpponent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(showMyCardsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showOpponentCardsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void drawPileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawPileButtonActionPerformed
//
    }//GEN-LAST:event_drawPileButtonActionPerformed

    private void passTurnToNextPlayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passTurnToNextPlayerButtonActionPerformed
//
    }//GEN-LAST:event_passTurnToNextPlayerButtonActionPerformed

    private void viewCardsInBankButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCardsInBankButtonActionPerformed
//
    }//GEN-LAST:event_viewCardsInBankButtonActionPerformed

    private void showAllSetsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllSetsButtonActionPerformed
//
    }//GEN-LAST:event_showAllSetsButtonActionPerformed

    private void viewCardsInHandButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCardsInHandButtonActionPerformed
//
    }//GEN-LAST:event_viewCardsInHandButtonActionPerformed

    private void showMyCardsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showMyCardsButtonActionPerformed
//
    }//GEN-LAST:event_showMyCardsButtonActionPerformed

    private void showOpponentCardsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showOpponentCardsButtonActionPerformed
//
    }//GEN-LAST:event_showOpponentCardsButtonActionPerformed

    private void playPileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playPileButtonActionPerformed
//
    }//GEN-LAST:event_playPileButtonActionPerformed

    private void remindTurnToOpponentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remindTurnToOpponentActionPerformed
//
    }//GEN-LAST:event_remindTurnToOpponentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void invokeMonopolyDealHomeScreen() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonopolyDealHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MonopolyDealHomeScreen().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea activityArea;
    private javax.swing.JLabel countOfCardsInAllSetsLabel;
    private javax.swing.JLabel countOfCardsInDrawPileLabel;
    private javax.swing.JLabel countOfCardsInPlayPileLabel;
    private javax.swing.JComboBox drawCardsComboBox;
    private javax.swing.JButton drawPileButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel numberOfCardsInBankLabel;
    private javax.swing.JLabel numberOfCardsInHandLabel;
    private javax.swing.JButton passTurnToNextPlayerButton;
    private javax.swing.JButton playPileButton;
    private javax.swing.JButton remindTurnToOpponent;
    private javax.swing.JButton showAllSetsButton;
    private javax.swing.JButton showMyCardsButton;
    private javax.swing.JButton showOpponentCardsButton;
    private javax.swing.JLabel sumOfValueOfCardsInBankLabel;
    private javax.swing.JComboBox toggleActivityComboBox;
    private javax.swing.JLabel totalNumberOfDifferentSetsLabel;
    private javax.swing.JLabel turnIndicatorLabel;
    private javax.swing.JButton viewCardsInBankButton;
    private javax.swing.JButton viewCardsInHandButton;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the activityArea
     */
    public javax.swing.JTextArea getActivityArea() {
        return activityArea;
    }

    /**
     * @param activityArea the activityArea to set
     */
    public void setActivityArea(javax.swing.JTextArea activityArea) {
        this.activityArea = activityArea;
    }

    /**
     * @return the countOfCardsInAllSetsLabel
     */
    public javax.swing.JLabel getCountOfCardsInAllSetsLabel() {
        return countOfCardsInAllSetsLabel;
    }

    /**
     * @param countOfCardsInAllSetsLabel the countOfCardsInAllSetsLabel to set
     */
    public void setCountOfCardsInAllSetsLabel(javax.swing.JLabel countOfCardsInAllSetsLabel) {
        this.countOfCardsInAllSetsLabel = countOfCardsInAllSetsLabel;
    }

    /**
     * @return the countOfCardsInDrawPileLabel
     */
    public javax.swing.JLabel getCountOfCardsInDrawPileLabel() {
        return countOfCardsInDrawPileLabel;
    }

    /**
     * @param countOfCardsInDrawPileLabel the countOfCardsInDrawPileLabel to set
     */
    public void setCountOfCardsInDrawPileLabel(javax.swing.JLabel countOfCardsInDrawPileLabel) {
        this.countOfCardsInDrawPileLabel = countOfCardsInDrawPileLabel;
    }

    /**
     * @return the countOfCardsInPlayPileLabel
     */
    public javax.swing.JLabel getCountOfCardsInPlayPileLabel() {
        return countOfCardsInPlayPileLabel;
    }

    /**
     * @param countOfCardsInPlayPileLabel the countOfCardsInPlayPileLabel to set
     */
    public void setCountOfCardsInPlayPileLabel(javax.swing.JLabel countOfCardsInPlayPileLabel) {
        this.countOfCardsInPlayPileLabel = countOfCardsInPlayPileLabel;
    }

    /**
     * @return the drawCardsComboBox
     */
    public javax.swing.JComboBox getDrawCardsComboBox() {
        return drawCardsComboBox;
    }

    /**
     * @param drawCardsComboBox the drawCardsComboBox to set
     */
    public void setDrawCardsComboBox(javax.swing.JComboBox drawCardsComboBox) {
        this.drawCardsComboBox = drawCardsComboBox;
    }

    /**
     * @return the numberOfCardsInBankLabel
     */
    public javax.swing.JLabel getNumberOfCardsInBankLabel() {
        return numberOfCardsInBankLabel;
    }

    /**
     * @param numberOfCardsInBankLabel the numberOfCardsInBankLabel to set
     */
    public void setNumberOfCardsInBankLabel(javax.swing.JLabel numberOfCardsInBankLabel) {
        this.numberOfCardsInBankLabel = numberOfCardsInBankLabel;
    }

    /**
     * @return the numberOfCardsInHandLabel
     */
    public javax.swing.JLabel getNumberOfCardsInHandLabel() {
        return numberOfCardsInHandLabel;
    }

    /**
     * @param numberOfCardsInHandLabel the numberOfCardsInHandLabel to set
     */
    public void setNumberOfCardsInHandLabel(javax.swing.JLabel numberOfCardsInHandLabel) {
        this.numberOfCardsInHandLabel = numberOfCardsInHandLabel;
    }

    /**
     * @return the sumOfValueOfCardsInBankLabel
     */
    public javax.swing.JLabel getSumOfValueOfCardsInBankLabel() {
        return sumOfValueOfCardsInBankLabel;
    }

    /**
     * @param sumOfValueOfCardsInBankLabel the sumOfValueOfCardsInBankLabel to set
     */
    public void setSumOfValueOfCardsInBankLabel(javax.swing.JLabel sumOfValueOfCardsInBankLabel) {
        this.sumOfValueOfCardsInBankLabel = sumOfValueOfCardsInBankLabel;
    }

    /**
     * @return the toggleActivityComboBox
     */
    public javax.swing.JComboBox getToggleActivityComboBox() {
        return toggleActivityComboBox;
    }

    /**
     * @param toggleActivityComboBox the toggleActivityComboBox to set
     */
    public void setToggleActivityComboBox(javax.swing.JComboBox toggleActivityComboBox) {
        this.toggleActivityComboBox = toggleActivityComboBox;
    }

    /**
     * @return the totalNumberOfDifferentSetsLabel
     */
    public javax.swing.JLabel getTotalNumberOfDifferentSetsLabel() {
        return totalNumberOfDifferentSetsLabel;
    }

    /**
     * @param totalNumberOfDifferentSetsLabel the totalNumberOfDifferentSetsLabel to set
     */
    public void setTotalNumberOfDifferentSetsLabel(javax.swing.JLabel totalNumberOfDifferentSetsLabel) {
        this.totalNumberOfDifferentSetsLabel = totalNumberOfDifferentSetsLabel;
    }

    /**
     * @return the turnIndicatorLabel
     */
    public javax.swing.JLabel getTurnIndicatorLabel() {
        return turnIndicatorLabel;
    }

    /**
     * @param turnIndicatorLabel the turnIndicatorLabel to set
     */
    public void setTurnIndicatorLabel(javax.swing.JLabel turnIndicatorLabel) {
        this.turnIndicatorLabel = turnIndicatorLabel;
    }
}
